permalink: /:year-:month-:day/:title/

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]



paginate: 10
paginate_path: ":num"
baseurl: ""



title: "Record Linkage blog"
email: "razvnpp@gmail.com"
description: "Boldly link what nobody had linked before."
github_username:  "RazvanML"
swiftype_searchId: "ncwR9a8S9CTx2q9SgsJm"
disqus_shortname: "razvanpopovici"



#url: "http://blog.rainyalley.com"
#imgrepo: "http://blog.rainyalley.com/static/img"
url: "http://razvanml.github.io/reco-link/"
imgrepo: "http://razvanml.github.io/reco-link/static/img"

